options:
  env:
  - SHORT_SHA=$SHORT_SHA
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - PACKAGE_VERSION=1.0.2
  - SUBPROJECT_ID=japanese-data-model
steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['build', '-p:Version=$PACKAGE_VERSION', '-c', 'Release', '-o', 'out']
#- name: 'gcr.io/my-web-apis/inspect-gs-builder'
- name: 'gcr.io/my-web-apis/upload-gs-builder'
- name: 'gcr.io/cloud-builders/dotnet'
  dir: JapaneseDataModel/out
  args: ['nuget', 'push', '*.nupkg', '-k', '$_NUGET_TOKEN', '-s', 'https://api.nuget.org/v3/index.json']

