options:
  env:
  - SUBPROJECT_ID=tanaka-corpus
  - SHORT_SHA=$SHORT_SHA
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
steps:
- name: 'gcr.io/cloud-builders/dotnet'
  dir: JapaneseDataModel
  args: ['restore']
- name: 'gcr.io/cloud-builders/dotnet'
  dir: JapaneseDataModel
  args: ['publish', '-c', 'Release', '-o', 'out']
- name: 'gcr.io/my-web-apis/upload-gs-builder'
  dir: JapaneseDataModel
- name: 'gcr.io/my-web-apis/inspect-gs-builder'
  dir: JapaneseDataModel
- name: 'gcr.io/cloud-builders/dotnet'
  dir: JapaneseDataModel/out/Release
  args: ['nuget', 'push', 'JapaneseDataModel.1.0.0.nupkg', '-k', '$_NUGET_TOKEN']


 