options:
  env:
  - SHORT_SHA=$SHORT_SHA
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
  - PACKAGE_VERSION=1.0.2
  - SUBPROJECT_ID=japanese-data-model
steps:
- name: 'gcr.io/my-web-apis/dotnet-build-builder'
- name: 'gcr.io/my-web-apis/upload-gs-builder'
- name: 'gcr.io/cloud-builders/dotnet'
  dir: out
  args: ['nuget', 'push', '*nupkg', '-k', '$_NUGET_TOKEN', '-s', 'https://api.nuget.org/v3/index.json']

